name: Deploy Prisma Migrations

on:
  push:
    branches:
      - main

jobs:
  prisma-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.7.0
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Deploy Prisma migrations
        run: pnpm dlx prisma migrate deploy --schema=prisma/schema.prisma
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DIRECT_URL: ${{ secrets.DIRECT_URL }}
